In [28]:
!pip install numpy
!pip install pandas

Requirement already satisfied: numpy in c:\users\nayani tharushika\appdata\local\programs\python\python312\lib\site-packages (1.26.4)
Requirement already satisfied: pandas in c:\users\nayani tharushika\appdata\local\programs\python\python312\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\nayani tharushika\appdata\local\programs\python\python312\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\nayani tharushika\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\nayani tharushika\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\nayani tharushika\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in c:\users\nayani tharushika\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [29]:
import numpy as np
import pandas as pd

In [30]:
data1 = pd.read_csv('CBWDB.csv', encoding='latin-1')

In [31]:
data1.head()

,SEC,Age(years),Height(cm),Bgroup,Parity,ANC,Iwt(kg),FWt(kg),IBP_sys,IBP_dias,FBP_sys,FBP_dias,IHb(gm%),FHb(gm%),BS(RBS),Term/Preterm,Sex,BWt(kg),LNH
0,BPL,23.0,146.0,A(+ve),1.0,4.0,34.0,42.0,116.0,78.0,120.0,70.0,10.0,13.2,90.0,T,F,2.7,2.0
1,BPL,25.0,165.0,NIL,1.0,3.0,68.0,71.0,96.0,70.0,110.0,72.0,10.4,11.0,96.0,T,M,2.9,2.0
2,BPL,24.0,155.0,B(+ve),1.0,3.0,49.0,55.0,91.0,52.0,110.0,70.0,11.0,11.6,102.0,T,M,2.4,1.0
3,BPL,19.0,154.0,NIL,1.0,2.0,49.0,50.0,90.0,52.0,100.0,60.0,10.0,10.6,103.0,T,F,2.6,2.0
4,BPL,21.0,150.0,NIL,1.0,4.0,41.0,48.0,100.0,60.0,110.0,70.0,9.0,10.2,99.0,T,F,2.3,1.0

In [32]:
data1.shape

(1800, 19)

In [33]:
data1.isnull().sum()

SEC              650
Age(years)        14
Height(cm)       273
Bgroup          1002
Parity            33
ANC               19
Iwt(kg)           49
FWt(kg)           61
IBP_sys           40
IBP_dias          40
FBP_sys           51
FBP_dias          52
IHb(gm%)         405
FHb(gm%)         407
BS(RBS)         1192
Term/Preterm     838
Sex              658
BWt(kg)          728
LNH              728
dtype: int64

In [34]:
data2 = data1.dropna()
data2.isnull().sum()

SEC             0
Age(years)      0
Height(cm)      0
Bgroup          0
Parity          0
ANC             0
Iwt(kg)         0
FWt(kg)         0
IBP_sys         0
IBP_dias        0
FBP_sys         0
FBP_dias        0
IHb(gm%)        0
FHb(gm%)        0
BS(RBS)         0
Term/Preterm    0
Sex             0
BWt(kg)         0
LNH             0
dtype: int64

In [35]:
data2.shape

(487, 19)

In [36]:
data2.head()

,SEC,Age(years),Height(cm),Bgroup,Parity,ANC,Iwt(kg),FWt(kg),IBP_sys,IBP_dias,FBP_sys,FBP_dias,IHb(gm%),FHb(gm%),BS(RBS),Term/Preterm,Sex,BWt(kg),LNH
0,BPL,23.0,146.0,A(+ve),1.0,4.0,34.0,42.0,116.0,78.0,120.0,70.0,10.0,13.2,90.0,T,F,2.7,2.0
1,BPL,25.0,165.0,NIL,1.0,3.0,68.0,71.0,96.0,70.0,110.0,72.0,10.4,11.0,96.0,T,M,2.9,2.0
2,BPL,24.0,155.0,B(+ve),1.0,3.0,49.0,55.0,91.0,52.0,110.0,70.0,11.0,11.6,102.0,T,M,2.4,1.0
3,BPL,19.0,154.0,NIL,1.0,2.0,49.0,50.0,90.0,52.0,100.0,60.0,10.0,10.6,103.0,T,F,2.6,2.0
4,BPL,21.0,150.0,NIL,1.0,4.0,41.0,48.0,100.0,60.0,110.0,70.0,9.0,10.2,99.0,T,F,2.3,1.0

In [37]:
data3 = data2.drop(['Sex'],axis='columns')
data3.shape

(487, 18)

In [38]:
data3.head()

,SEC,Age(years),Height(cm),Bgroup,Parity,ANC,Iwt(kg),FWt(kg),IBP_sys,IBP_dias,FBP_sys,FBP_dias,IHb(gm%),FHb(gm%),BS(RBS),Term/Preterm,BWt(kg),LNH
0,BPL,23.0,146.0,A(+ve),1.0,4.0,34.0,42.0,116.0,78.0,120.0,70.0,10.0,13.2,90.0,T,2.7,2.0
1,BPL,25.0,165.0,NIL,1.0,3.0,68.0,71.0,96.0,70.0,110.0,72.0,10.4,11.0,96.0,T,2.9,2.0
2,BPL,24.0,155.0,B(+ve),1.0,3.0,49.0,55.0,91.0,52.0,110.0,70.0,11.0,11.6,102.0,T,2.4,1.0
3,BPL,19.0,154.0,NIL,1.0,2.0,49.0,50.0,90.0,52.0,100.0,60.0,10.0,10.6,103.0,T,2.6,2.0
4,BPL,21.0,150.0,NIL,1.0,4.0,41.0,48.0,100.0,60.0,110.0,70.0,9.0,10.2,99.0,T,2.3,1.0

In [39]:
data3['SEC'].value_counts()

SEC
BPL    333
APL    154
Name: count, dtype: int64

In [40]:
data3['Bgroup'].value_counts()

Bgroup
NIL        230
B(+ve)      89
A(+ve)      63
O(+VE)      62
AB(+ve)     20
O(+ve)      13
B(+VE)       3
A(+VE)       3
B+(+ve)      1
A(-ve)       1
B(-ve)       1
O(-ve)       1
Name: count, dtype: int64

In [41]:
data3['Term/Preterm'].value_counts()

Term/Preterm
T     428
PT     59
Name: count, dtype: int64

In [45]:
data3.head()

,SEC,Age(years),Height(cm),Bgroup,Parity,ANC,Iwt(kg),FWt(kg),IBP_sys,IBP_dias,FBP_sys,FBP_dias,IHb(gm%),FHb(gm%),BS(RBS),Term/Preterm,BWt(kg),LNH
0,BPL,23.0,146.0,A(+ve),1.0,4.0,34.0,42.0,116.0,78.0,120.0,70.0,10.0,13.2,90.0,T,2.7,2.0
1,BPL,25.0,165.0,NIL,1.0,3.0,68.0,71.0,96.0,70.0,110.0,72.0,10.4,11.0,96.0,T,2.9,2.0
2,BPL,24.0,155.0,B(+ve),1.0,3.0,49.0,55.0,91.0,52.0,110.0,70.0,11.0,11.6,102.0,T,2.4,1.0
3,BPL,19.0,154.0,NIL,1.0,2.0,49.0,50.0,90.0,52.0,100.0,60.0,10.0,10.6,103.0,T,2.6,2.0
4,BPL,21.0,150.0,NIL,1.0,4.0,41.0,48.0,100.0,60.0,110.0,70.0,9.0,10.2,99.0,T,2.3,1.0

In [46]:
data = pd.get_dummies(data3)

In [47]:
data.head()

,Age(years),Height(cm),Parity,ANC,Iwt(kg),FWt(kg),IBP_sys,IBP_dias,FBP_sys,FBP_dias,...,Bgroup_B(+VE),Bgroup_B(+ve),Bgroup_B(-ve),Bgroup_B+(+ve),Bgroup_NIL,Bgroup_O(+VE),Bgroup_O(+ve),Bgroup_O(-ve),Term/Preterm_PT,Term/Preterm_T
0,23.0,146.0,1.0,4.0,34.0,42.0,116.0,78.0,120.0,70.0,...,False,False,False,False,False,False,False,False,False,True
1,25.0,165.0,1.0,3.0,68.0,71.0,96.0,70.0,110.0,72.0,...,False,False,False,False,True,False,False,False,False,True
2,24.0,155.0,1.0,3.0,49.0,55.0,91.0,52.0,110.0,70.0,...,False,True,False,False,False,False,False,False,False,True
3,19.0,154.0,1.0,2.0,49.0,50.0,90.0,52.0,100.0,60.0,...,False,False,False,False,True,False,False,False,False,True
4,21.0,150.0,1.0,4.0,41.0,48.0,100.0,60.0,110.0,70.0,...,False,False,False,False,True,False,False,False,False,True

In [50]:
X = data.drop('BWt(kg)', axis=1)
y = data['BWt(kg)']

In [51]:
X.head()

,Age(years),Height(cm),Parity,ANC,Iwt(kg),FWt(kg),IBP_sys,IBP_dias,FBP_sys,FBP_dias,...,Bgroup_B(+VE),Bgroup_B(+ve),Bgroup_B(-ve),Bgroup_B+(+ve),Bgroup_NIL,Bgroup_O(+VE),Bgroup_O(+ve),Bgroup_O(-ve),Term/Preterm_PT,Term/Preterm_T
0,23.0,146.0,1.0,4.0,34.0,42.0,116.0,78.0,120.0,70.0,...,False,False,False,False,False,False,False,False,False,True
1,25.0,165.0,1.0,3.0,68.0,71.0,96.0,70.0,110.0,72.0,...,False,False,False,False,True,False,False,False,False,True
2,24.0,155.0,1.0,3.0,49.0,55.0,91.0,52.0,110.0,70.0,...,False,True,False,False,False,False,False,False,False,True
3,19.0,154.0,1.0,2.0,49.0,50.0,90.0,52.0,100.0,60.0,...,False,False,False,False,True,False,False,False,False,True
4,21.0,150.0,1.0,4.0,41.0,48.0,100.0,60.0,110.0,70.0,...,False,False,False,False,True,False,False,False,False,True

In [53]:
y.head()

0    2.7
1    2.9
2    2.4
3    2.6
4    2.3
Name: BWt(kg), dtype: float64

In [55]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\nayani tharushika\appdata\local\programs\python\python312\lib\site-packages (1.4.1.post1)
Requirement already satisfied: numpy<2.0,>=1.19.5 in c:\users\nayani tharushika\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (1.26.4)
Requirement already satisfied: scipy>=1.6.0 in c:\users\nayani tharushika\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (1.12.0)
Requirement already satisfied: joblib>=1.2.0 in c:\users\nayani tharushika\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\nayani tharushika\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (3.3.0)

In [56]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25)

In [57]:
X_train.shape, X_test.shape

((365, 30), (122, 30))

In [58]:
def model_acc(model):
    model.fit(X_train, y_train)
    acc = model.score(X_test, y_test)
    print(str(model)+ ' --> ' +str(acc))

In [59]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
model_acc(lr)

from sklearn.linear_model import Lasso
lasso = Lasso()
model_acc(lasso)

from sklearn.tree import DecisionTreeRegressor
dt = DecisionTreeRegressor()
model_acc(dt)

from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor()
model_acc(rf)

LinearRegression() --> 0.5371629367839093
Lasso() --> 0.015573880765732184
DecisionTreeRegressor() --> 0.18279995627007362
RandomForestRegressor() --> 0.5059954811916996

In [60]:
from sklearn.model_selection import GridSearchCV

parameters = {'n_estimators':[10, 50, 100],
              'criterion':['squared_error','absolute_error','poisson']}

grid_obj = GridSearchCV(estimator=rf, param_grid=parameters)

grid_fit = grid_obj.fit(X_train, y_train)

best_model = grid_fit.best_estimator_

best_model.score(X_test, y_test)

0.49536739269178387

In [62]:
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import RandomizedSearchCV
import numpy as np

# Pipeline for scaling and model
pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('rf', RandomForestRegressor(random_state=42))
])

# Expanded parameter grid for Random Forest
parameters = {
    'rf__n_estimators': [50, 100, 200],
    'rf__criterion': ['squared_error', 'absolute_error'],
    'rf__max_depth': [None, 10, 20, 30],
    'rf__min_samples_split': [2, 5, 10],
    'rf__min_samples_leaf': [1, 2, 4],
    'rf__max_features': ['sqrt', 'log2', None],
    'rf__bootstrap': [True, False]
}

# RandomizedSearchCV with cross-validation
random_search = RandomizedSearchCV(estimator=pipeline, param_distributions=parameters, 
                                   n_iter=100, cv=5, n_jobs=-1, scoring='r2', random_state=42)
random_search.fit(X_train, y_train)

# Best model performance
best_model = random_search.best_estimator_
best_model_score = best_model.score(X_test, y_test)

print(f"Best Model Score: {best_model_score}")
print(f"Best Parameters: {random_search.best_params_}")

Best Model Score: 0.5107047045866193
Best Parameters: {'rf__n_estimators': 100, 'rf__min_samples_split': 10, 'rf__min_samples_leaf': 1, 'rf__max_features': None, 'rf__max_depth': 30, 'rf__criterion': 'absolute_error', 'rf__bootstrap': True}

In [64]:
import pickle
with open('predictor.pickle', 'wb') as file:
    pickle.dump(best_model, file)

In [68]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=10)

In [69]:
from sklearn.linear_model import LinearRegression
lr_clf = LinearRegression()
lr_clf.fit(X_train,y_train)
lr_clf.score(X_test,y_test)

0.5877710294896863

In [75]:
def predict_weight(Bgroup,Age,Height,Parity):    
    loc_index = np.where(X.columns==Bgroup)[0][0]

    x = np.zeros(len(X.columns))
    x[0] = Age
    x[1] = Height
    x[2] = Parity
    if loc_index >= 0:
        x[loc_index] = 1

    return lr_clf.predict([x])[0]

In [80]:
predict_weight('Bgroup_B(+VE)',25,153,1)

C:\Users\Nayani Tharushika\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

0.8193317675443309

In [81]:
def predict_weight(Bgroup, Age, Height, Parity):    
    # Check if Bgroup is in the columns
    if Bgroup not in X.columns:
        raise ValueError(f"Bgroup {Bgroup} is not a valid column name in X")

    # Get the index of Bgroup column
    loc_index = np.where(X.columns == Bgroup)[0][0]

    # Initialize the input array with zeros
    x = np.zeros(len(X.columns))
    
    # Assign the values to the input array
    x[0] = Age
    x[1] = Height
    x[2] = Parity

    # Set the value for the Bgroup column
    if loc_index >= 0:
        x[loc_index] = 1

    # Predict the weight
    return lr_clf.predict([x])[0]

# Example call
predict_weight('Bgroup_B(+VE)', 30, 153, 1)

C:\Users\Nayani Tharushika\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

0.8300521588863986

In [83]:
X_train.columns

Index(['Age(years)', 'Height(cm)', 'Parity', 'ANC', 'Iwt(kg)', 'FWt(kg)',
       'IBP_sys', 'IBP_dias', 'FBP_sys', 'FBP_dias', 'IHb(gm%)', 'FHb(gm%)',
       'BS(RBS)', 'LNH', 'SEC_APL', 'SEC_BPL', 'Bgroup_A(+VE)',
       'Bgroup_A(+ve)', 'Bgroup_A(-ve)', 'Bgroup_AB(+ve)', 'Bgroup_B(+VE)',
       'Bgroup_B(+ve)', 'Bgroup_B(-ve)', 'Bgroup_B+(+ve)', 'Bgroup_NIL',
       'Bgroup_O(+VE)', 'Bgroup_O(+ve)', 'Bgroup_O(-ve)', 'Term/Preterm_PT',
       'Term/Preterm_T'],
      dtype='object')

In [85]:
best_model.predict([[25,160,1,1,34,42,55,91,52,110,70,11,11.6,102,0,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0]])

ValueError: X has 30 features, but StandardScaler is expecting 495 features as input.